routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::group(['middleware' => ['auth:sanctum','verified']], function() {
    Route::resources([
        'users' => 'App\Http\Controllers\UserController',
    ]);

    Route::get('/cme', function () {
        return view('cme');
    })->name('cme');

    Route::get('/video', function () {
        return view('video');
    })->name('video');

    Route::get('/schedule', function () {
        return view('schedule');
    })->name('schedule');

    Route::get('/livestream/1', function () {
        return view('livestream1');
    })->name('livestream1');

    Route::get('/livestream/2', function () {
        return view('livestream2');
    })->name('livestream2');
    
    Route::get('/games', function () {
        return view('games');
    })->name('games');
    
    Route::get('/exhibit', function () {
        return view('exhibit');
    })->name('exhibit');

    Route::get('/exhibit/1', function () {
        return view('exhibit1');
    })->name('exhibit1');

    Route::get('/exhibit/2', function () {
        return view('exhibit2');
    })->name('exhibit2');

    Route::get('/exhibit/3', function () {
        return view('exhibit3');
    })->name('exhibit3');

    Route::get('/exhibit/4', function () {
        return view('exhibit4');
    })->name('exhibit4');

    Route::get('/exhibit/5', function () {
        return view('exhibit5');
    })->name('exhibit5');

    Route::get('/medhub', function () {
        return view('medhub');
    })->name('medhub');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Http/Livewire/Exhibit1.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Exhibit1 extends Component
{
    public $content;
    public $vid_link;

    public function mount()
    {
        $this->content = 0;
        $this->vid_link = 'https://player.vimeo.com/video/703142793';
    }

    public function changeContent($content)
    {
        $this->content = $content;

        switch ($this->content) {
            case 1:
                $this->vid_link = 'https://player.vimeo.com/video/703142852';
                break;

            case 2:
                $this->vid_link = 'https://player.vimeo.com/video/703142925';
                break;

            case 3:
                $this->vid_link = 'https://player.vimeo.com/video/703143992';
                break;

            case 4:
                $this->vid_link = 'https://player.vimeo.com/video/703143716';
                break;

            case 5:
                $this->vid_link = 'https://player.vimeo.com/video/704084090';
                break;
            
            default:
                $this->vid_link = 'https://player.vimeo.com/video/703142793';
                break;
        }
    }

    public function render()
    {
        return view('livewire.exhibit1');
    }
}

app/Http/Livewire/Exhibit2.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Exhibit2 extends Component
{
    public $content;
    public $vid_link = 'https://player.vimeo.com/video/703142543';

    public function mount()
    {
        $this->content = 0;
    }

    public function changeContent($content)
    {
        $this->content = $content;

        switch ($this->content) {
            case 2:
                $this->vid_link = 'https://player.vimeo.com/video/703142654';
                break;
                
            default:
                $this->vid_link = 'https://player.vimeo.com/video/703142543';
                break;
        }
    }

    public function render()
    {
        return view('livewire.exhibit2');
    }
}

app/Http/Livewire/Exhibit3.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Exhibit3 extends Component
{
    public $content;
    public $vid_link = 'https://player.vimeo.com/video/703569860';

    public function mount()
    {
        $this->content = 0;
    }

    public function changeContent($content)
    {
        $this->content = $content;
    }

    public function render()
    {
        return view('livewire.exhibit3');
    }
}

app/Http/Livewire/Exhibit4.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Exhibit4 extends Component
{
    public function render()
    {
        return view('livewire.exhibit4');
    }
}

app/Http/Livewire/Exhibit5.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Exhibit5 extends Component
{
    public $content;
    public $vid_link;

    public function mount()
    {
        $this->content = 0;
    }

    public function changeContent($content)
    {
        $this->content = $content;

        switch ($this->content) {
            case 2:
                $this->vid_link = 'https://player.vimeo.com/video/703569612';
                break;

            case 3:
                $this->vid_link = 'https://player.vimeo.com/video/704084090';
                break;

            default:
                $this->vid_link = 'https://player.vimeo.com/video/703567848';
                break;
        }
    }

    public function render()
    {
        return view('livewire.exhibit5');
    }
}

app/Http/Livewire/GamePage.php
<?php

namespace App\Http\Livewire;

use App\Models\Games;
use Livewire\Component;

class GamePage extends Component
{
    protected $response;

    public $start = false;
    public $time = null;
    public $start_time = null;
    public $end_time = null;
    public $questions = [];
    public $answered = 0;
    public $previous = 0;
    public $score = 0;
    public $quiz = 0;

    public $headers = array('Fullname','Score','Time in Seconds');

    public $questionData = array(
        [
            'question' => 'Which of the following substances enhance iron absorption?',
            'answers' => array('Polyphenois in tea','Vitamin C','Vitamin A','Sodium Chloride'),
            'correct_answer' => 'Vitamin C'
        ],
        [
            'question' => 'Which of the following is a possible consequence of iron defeciency anemia in pregnant women?',
            'answers' => array('Intrauterine fetal death','Ectopic pregnancy','Pre-eclampsia','All of the above'),
            'correct_answer' => 'Pre-eclampsia'
        ],
        [
            'question' => 'Where does iron absorption occur in the body?',
            'answers' => array('Large intestine','Liver','Small intestine','Stomach'),
            'correct_answer' => 'Small intestine'
        ],
        [
            'question' => 'What virus is the most common cause of Common cold? ',
            'answers' => array('Rhinovirus','Coronavirus','Adenovirus','Respiratory Syncytial virus'),
            'correct_answer' => 'Rhinovirus'
        ],
        [
            'question' => 'Do you know how many times an average person suffers from cold in their entire lifetime? ',
            'answers' => array('100 times','1000 times','200 times','300 times'),
            'correct_answer' => '200 times'
        ],
        [
            'question' => 'The total symptom  duration of cold during person’s life is:',
            'answers' => array('1 year','2 years','>=3 years','10 years'),
            'correct_answer' => '>=3 years'
        ],
        [
            'question' => 'How much sleep do adults (18-64 y) need on average?',
            'answers' => array('8-10 hrs','7-9 hrs','7-8 hrs','No recommendation'),
            'correct_answer' => '7-9 hrs'
        ],
        [
            'question' => 'Melatonin production peaks in children and at what age (yrs) does it decrease less than half the melatonin we did as a child?',
            'answers' => array('50-60 years','20 years','After our 30s','70-80s'),
            'correct_answer' => 'After our 30s'
        ],
        [
            'question' => 'Melatonin is a hormone produced mainly by the:',
            'answers' => array('Suprachiasmic nucleus','Pineal gland','Adrenal glands','Hypothalamus'),
            'correct_answer' => 'Pineal gland'
        ],
        [
            'question' => 'What type of nerves have the fastest nerve conduction velocity?',
            'answers' => array('Unmyelinated nerves','Myelinated nerves','Damaged nerves','Long nerves'),
            'correct_answer' => 'Myelinated nerves'
        ],
        [
            'question' => 'If ____ or more of the nerve fibers are damaged, nerve regeneration is not possible anymore and the so called “point of no return” is reached',
            'answers' => array('80%','50%','65%','40%'),
            'correct_answer' => '50%'
        ],
        [
            'question' => 'What is the second most common cause of neuropathy?',
            'answers' => array('Diabetes','Idiopathic (unknown cause)','Infections','Alcohol'),
            'correct_answer' => 'Idiopathic (unknown cause)'
        ],
        [
            'question' => 'Which does not describe Vitamin B1?',
            'answers' => array('Involved in the energy metabolism','Involved in the metabolism of neurotransmitters','Fat Soluble','Involved in nerve stimulation'),
            'correct_answer' => 'Fat Soluble'
        ],
        [
            'question' => 'What does neurotropic mean',
            'answers' => array('Having an affinity to and nourishing the nervous system','Being water soluble ','Having a positive charge in the chemical structure','Being rare in the nature'),
            'correct_answer' => 'Having an affinity to and nourishing the nervous system'
        ],
        [
            'question' => 'Title of this event?',
            'answers' => array('Neuropathy?','P&G Health Medical Events','Breaking the wave','None of the Above'),
            'correct_answer' => 'Breaking the wave'
        ]
    );

    public function mount()
    {
        $random_numbers = array_rand($this->questionData,5);

        foreach($random_numbers as $rand)
        {
            array_push($this->questions,$this->questionData[$rand]);
        }
    }


    public function changeStatus($status)
    {
        $this->start = $status;

        if($this->start == true)
        {
            $this->start_time = microtime(true); 
        } else {
            $this->end_time = microtime(true);
            $this->time = intval($this->end_time - $this->start_time);
        }
    }

    public function nextQuestion()
    {
        $this->previous = $this->score;
        
        if($this->quiz < 4)
        {
            $this->quiz++;
        } else {
            
            $this->changeStatus(false);

            $player = Games::where('user_id',auth()->user()->id)->first();

            if(is_null($player))
            {
                Games::create([
                    'user_id' => auth()->user()->id,
                    'prc_number' => auth()->user()->prc_number,
                    'name' => auth()->user()->name,
                    'email' => auth()->user()->email,
                    'score' => $this->score,
                    'time' => $this->time
                ]);
            } else {
                if($player->score <= $this->score)
                {
                    $player->score = $this->score;
                    
                    if($player->time > $this->time)
                    {
                        $player->time = $this->time;
                    }

                    $player->save();
                }
            }

            return redirect()->route('games');
        }
    }

    public function answerQuestion($answer)
    {
        if($this->questions[$this->quiz]['correct_answer'] == $answer)
        {
            $this->score++;
        }

        if($this->answered <= 4)
        {
            $this->answered++;
        }
    }

    public function render()
    {
        $this->response = Games::orderByDesc('score')->take(5);
        $this->response = $this->response->orderBy('time')->get();

        return view('livewire.game-page',[
            'response' => $this->response,
        ]);
    }
}

app/Http/Livewire/Hubmed.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Hubmed extends Component
{
    public function render()
    {
        return view('livewire.hubmed');
    }
}

app/Http/Livewire/Medhub.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Medhub extends Component
{
    public $content;
    public $vid_link;

    public function mount()
    {
        $this->content = 0;
        $this->content_link = 'https://pghealthmedicalevents.com/public/pdf/Early_Intervention.pdf#toolbar=0&navpanes=0';
    }

    public function changeContent($content)
    {
        $this->content = $content;

        switch ($this->content) {
            case 1:
                $this->content_link = 'https://player.vimeo.com/video/704335293?h=6eb1e7fc36&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479';
                break;

            case 2:
                $this->content_link = 'https://pghealthmedicalevents.com/public/pdf/5stepstoPNdiagnosis.pdf#toolbar=0&navpanes=0';
                break;
            
            case 3:
                $this->content_link = 'https://pghealthmedicalevents.com/public/pdf/5stepstoPNdiagnosis.pdf#toolbar=0&navpanes=0';
                break;

            case 4:
                $this->content_link = 'https://pghealthmedicalevents.com/public/pdf/HowToDiagnosisPN.pdf#toolbar=0&navpanes=0';
                break;

            case 5:
                $this->content_link = 'https://pghealthmedicalevents.com/public/pdf/NeurotropicBVitaminsinNerveHealth.pdf#toolbar=0&navpanes=0';
                break;

            case 6:
                $this->content_link = 'https://pghealthmedicalevents.com/public/pdf/PNSymptomsandRiskGroups.pdf#toolbar=0&navpanes=0';
                break;

            case 7:
                $this->content_link = 'https://pghealthmedicalevents.com/public/img/3_4_1.jpg';
                break;

            case 8:
                $this->content_link = 'https://player.vimeo.com/video/704336026?h=cea27b6b88&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479';
                break;

            case 9:
                $this->content_link = 'https://player.vimeo.com/video/704335716?h=cea57d9e92&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479';
                break;
            
            default:
                $this->content_link = 'https://pghealthmedicalevents.com/public/pdf/Early_Intervention.pdf#toolbar=0&navpanes=0';
                break;
        }
    }

    public function render()
    {
        return view('livewire.medhub');
    }
}

app/Http/Livewire/UsersIndex.php
<?php

namespace App\Http\Livewire;

use Carbon\Carbon;

use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;

class UsersIndex extends Component
{
    use WithPagination;

    protected $response;

    public $selectedData = null;
    public $editModal = false;
    public $search = null;

    public $headers = array('PRC Number','Fullname','Email Address','Role','Date Created','Status','Actions');
    
    public function boot()
    {
        $this->resetPage();
    }

    public function mount(User $users)
    {
        $this->resetPage();
        $this->response = $users->all();
    }

    public function updating()
    {
        $this->resetPage();
    }

    public function updated()
    {
        $this->resetPage();
    }

    public function renderRole($role)
    {
        $renderedRole = null;
        switch ($role) {
            case 0:
                $renderedRole = 'Admin';
                break;
            default:
                $renderedRole = 'User';
                break;
        }
        return $renderedRole;
    }

    public function renderStatus($status)
    {
        return !is_null($status) ? 'Verified' : 'Not Verified';
    }

    public function verifyUser($id)
    {
        $user = User::findOrFail($id);
        $user->email_verified_at = Carbon::now();
        $user->save();
    }

    public function verifyAll()
    {
        $users = User::where('email_verified_at',null)->get();

        foreach($users as $user)
        {
            $user->email_verified_at = Carbon::now();
            $user->save();
        }
    }

    public function render()
    {
        if(is_null($this->search)) {
            $this->response = User::paginate(5);
        } else {
            $this->response = User::search($this->search)->paginate(5);
        }

        return view('livewire.users-index',[
            'response' => $this->response,
        ]);
    }
}

resources/views/livewire/exhibit1.blade.php
<div>
    <div class="flex flex-row w-screen h-screen bg-transparent md:bg-white/50">
        <div class="hidden w-1/6 min-h-screen py-32 bg-white border-r-4 border-lime-400 md:block">
            <ul class="flex flex-col w-full space-y-6">
                <li class="flex items-center justify-center w-full px-6">
                    <img id="logo" src="https://pghealthmedicalevents.com/public/img/sangobionplus.png" class="w-auto h-20">
                </li>
                <li class="flex items-center justify-center w-full">
                    <ul class="space-y-2 list-none">
                        <li>
                            <button wire:click="changeContent(0)" type="button" class="flex flex-row items-center justify-center focus:outline-none {{$content == 0 ? 'text-lime-400 hover:text-gray-600' : 'text-gray-600 hover:text-lime-400'}}">
                                <span class="text-xs font-extrabold tracking-wide capitalize truncate">SANGOBION IRON + for ADULT</span>
                            </button>
                        </li>
                        <li>
                            <button wire:click="changeContent(1)" type="button" class="flex flex-row items-center justify-center focus:outline-none  {{$content == 1 ? 'text-lime-400 hover:text-gray-600' : 'text-gray-600 hover:text-lime-400'}}">
                                <span class="text-xs font-extrabold tracking-wide capitalize truncate">SANGOBION IRON + for ELDERLY</span>
                            </button>
                        </li>
                        <li>
                            <button wire:click="changeContent(2)" type="button" class="flex flex-row items-center justify-center focus:outline-none {{$content == 2 ? 'text-lime-400 hover:text-gray-600' : 'text-gray-600 hover:text-lime-400'}}">
                                <span class="text-xs font-extrabold tracking-wide capitalize truncate">SANGOBION IRON + for OB PREGNANT</span>
                            </button>
                        </li>
                        <li>
                            <button wire:click="changeContent(5)" type="button" class="flex flex-row items-center justify-center focus:outline-none  {{$content == 2 ? 'text-lime-400 hover:text-gray-600' : 'text-gray-600 hover:text-lime-400'}}">
                                <span class="text-xs font-extrabold tracking-wide capitalize truncate">SANGOBION ADOLESCENT VIDEO</span>
                            </button>
                        </li>
                    </ul>
                </li>
                <li class="flex items-center justify-center w-full px-6">
                    <img id="logo" src="https://pghealthmedicalevents.com/public/img/sangobionforte.png" class="w-auto h-20">
                </li>
                <li class="flex items-center justify-center w-full">
                    <ul class="space-y-2 list-none">
                        <li>
                            <button wire:click="changeContent(3)" type="button" class="flex flex-row items-center justify-center focus:outline-none {{$content == 3 ? 'text-lime-400 hover:text-gray-600' : 'text-gray-600 hover:text-lime-400'}}">
                                <span class="text-xs font-extrabold tracking-wide capitalize truncate">SANGOBION FORTE for OB PREGNANT</span>
                            </button>
                        </li>
                        <li>
                            <button wire:click="changeContent(4)" type="button" class="flex flex-row items-center justify-center focus:outline-none {{$content == 4 ? 'text-lime-400 hover:text-gray-600' : 'text-gray-600 hover:text-lime-400'}}">
                                <span class="text-xs font-extrabold tracking-wide capitalize truncate">SANGOBION FORTE for ANEMIA</span>
                            </button>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="hidden w-screen h-screen pt-24 bg-white/90 md:w-5/6 md:block">
            <div class="flex items-center justify-center w-full h-full">
                <div class="w-full h-full aspect-video">
                    <iframe class="w-full h-full" src="{{$vid_link}}" frameborder="0" allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
            </div>
        </div>
        <div class="block w-screen min-h-screen px-6 pb-4 overflow-y-auto pt-28 bg-white/90 md:hidden">
            <div class="flex flex-col w-full h-full space-y-6">
                <img id="logo" src="https://pghealthmedicalevents.com/public/img/sangobionplus.png" class="w-auto h-20">
                <div class="w-full h-full aspect-video">
                    <iframe class="w-full h-full" src="https://player.vimeo.com/video/703142793" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
                <div class="w-full h-full aspect-video">
                    <iframe class="w-full h-full" src="https://player.vimeo.com/video/703142852" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
                <div class="w-full h-full aspect-video">
                    <iframe class="w-full h-full" src="https://player.vimeo.com/video/703142925" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
                <img id="logo" src="https://pghealthmedicalevents.com/public/img/sangobionforte.png" class="w-auto h-20">
                <div class="w-full h-full aspect-video">
                    <iframe class="w-full h-full" src="https://player.vimeo.com/video/703143992" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
                <div class="w-full h-full aspect-video">
                    <iframe class="w-full h-full" src="https://player.vimeo.com/video/703143716" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
                <div class="w-full h-full aspect-video">
                    <iframe class="w-full h-full" src="https://player.vimeo.com/video/704084090" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/livewire/exhibit3.blade.php
<div>
    <div class="flex flex-row w-screen h-screen bg-white/50">
        <div class="hidden w-1/6 min-h-screen py-32 bg-white border-r-4 border-lime-400 md:block">
            <ul class="flex flex-col w-full space-y-6">
                <li class="flex items-center justify-center w-full px-6">
                    <img id="logo" src="https://pghealthmedicalevents.com/public/img/vicks.png" class="w-auto h-20">
                </li>
                <li class="flex items-center justify-center w-full">
                    <ul class="space-y-2 list-none">
                        <li>
                            <button wire:click="changeContent(0)" type="button" class="flex flex-row items-center justify-center focus:outline-none {{$content == 0 ? 'text-lime-400 hover:text-gray-600' : 'text-gray-600 hover:text-lime-400'}}">
                                <span class="text-xs font-extrabold tracking-wide capitalize truncate">VFD / VID</span>
                            </button>
                        </li>
                        <li>
                            <button wire:click="changeContent(1)" type="button" class="flex flex-row items-center justify-center focus:outline-none  {{$content == 1 ? 'text-lime-400 hover:text-gray-600' : 'text-gray-600 hover:text-lime-400'}}">
                                <span class="text-xs font-extrabold tracking-wide capitalize truncate">VICKS BRAND VIDEO</span>
                            </button>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="hidden w-screen h-screen pt-24 bg-white/90 md:w-5/6 md:block">
            @if($content == 0)
                <div class="w-full h-full">
                    <iframe src="https://pghealthmedicalevents.com/public/pdf/vfd.pdf#toolbar=0&navpanes=0" class="w-full h-full"></iframe>
                </div>
            @else
                <div class="flex items-center justify-center w-full h-full">
                    <div class="w-full h-full aspect-video">
                        <iframe class="w-full h-full" src="{{$vid_link}}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                </div>
            @endif
        </div>
        <div class="block w-screen h-full pt-32 space-y-2 bg-white/90 md:hidden">
            <div class="flex flex-col w-full h-full p-6 space-y-2">
                <img id="logo" src="https://pghealthmedicalevents.com/public/img/vicks.png" class="w-auto h-20">
                <iframe src="https://pghealthmedicalevents.com/public/pdf/vfd.pdf#toolbar=0&navpanes=0" class="w-full h-full"></iframe>
            </div>
            <div class="w-full h-full p-6">
                <div class="w-full h-full aspect-video">
                    <iframe class="w-full h-full" src="{{$vid_link}}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/livewire/users-index.blade.php
<div>
    <div class="flex flex-col p-6 bg-white border-b border-gray-200 sm:px-20">
        <div class="flex flex-row w-full space-x-2 border-b border-gray-500">
            <div class="flex w-full py-2 shadow-sm">
                <span class="inline-flex items-center px-3 text-sm text-gray-500 border border-r-0 border-gray-300 rounded-l-xl bg-gray-50">
                    <i class="fa-solid fa-magnifying-glass"></i>
                </span>
                <input wire:model="search" type="text" class="flex-1 block w-full border-gray-300 rounded-none focus:ring-teal-500 focus:border-teal-500 rounded-r-xl sm:text-sm" placeholder="Search something here...">
            </div>
            <div class="flex items-center justify-center w-auto">
                <button wire:click="verifyAll" type="button" class="px-2 py-1 border-2 border-gray-600 rounded-xl">
                    <i class="fa-solid fa-circle-check"></i>
                </button>
            </div>
            <div class="flex items-center justify-center w-auto">
                <a href="{{route('users.index')}}" class="px-2 py-1 border-2 border-gray-600 rounded-xl">
                    <i class="fa-solid fa-download"></i>
                </a>
            </div>
        </div>
        <div class="relative z-0 w-full my-6 overflow-x-auto shadow-md">
            <table class="w-full text-sm text-left text-gray-500 uppercase">
                <thead class="text-xs text-gray-700 uppercase bg-gray-50">
                    <tr>
                        @foreach($headers as $content)
                            <th scope="col" class="px-6 py-3">
                                {{$content}}
                            </th>
                        @endforeach
                    </tr>
                </thead>
                <tbody>
                    @foreach($response as $data)
                        <tr class="bg-white border-b hover:bg-lime-100">
                            <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                                {{$data->prc_number}}
                            </th>
                            <td class="px-6 py-4">
                                {{$data->name}}
                            </td>
                            <td class="px-6 py-4">
                                {{$data->email}}
                            </td>
                            <td class="px-6 py-4">
                                {{$this->renderRole($data->role)}}
                            </td>
                            <td class="px-6 py-4">
                                {{$data->created_at}}
                            </td>
                            <td class="px-6 py-4">
                                {{$this->renderStatus($data->email_verified_at)}}
                            </td>
                            <td class="flex flex-row px-6 py-4 space-x-2 text-center">
                                @if(is_null($data->email_verified_at))
                                <button wire:click="verifyUser({{$data->id}})" type="button">
                                    <i class="text-gray-700 fa-solid fa-thumbs-up"></i>
                                </button>
                                @endif
                                @if($data->id > 2)
                                <form method="POST" action="{{ route('users.destroy',$data->id) }}">
                                    @method('delete')
                                    @csrf
                                    <button type="submit">
                                        <i class="text-red-700 fa-solid fa-trash"></i>
                                    </button>
                                </form>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <div class="w-full h-auto py-2 border-t-2 border-gray-300">
            {{$response->links()}}
        </div>
    </div>
</div>